# -*- coding: utf-8 -*-
"""Streamlit_HeartDiseasePrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10p-_l0E1FWqVoFpTrBW5Qa9yioZ8Vjaz
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install streamlit

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlitapp.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import pickle
# 
# # Load model, scaler and column structure
# model = pickle.load(open("heart_model.pkl", "rb"))
# scaler = pickle.load(open("scaler.pkl", "rb"))
# model_columns = pickle.load(open("model_columns.pkl", "rb"))
# 
# st.title("❤️ Heart Disease Prediction App")
# st.write("Enter patient details below:")
# 
# # Patient ID
# patient_id = st.text_input("Patient ID")
# 
# input_data = {}
# 
# columns_to_use = [
#     'slope_of_peak_exercise_st_segment',
#     'thal',
#     'resting_blood_pressure',
#     'chest_pain_type',
#     'num_major_vessels',
#     'fasting_blood_sugar_gt_120_mg_per_dl',
#     'resting_ekg_results',
#     'serum_cholesterol_mg_per_dl',
#     'oldpeak_eq_st_depression',
#     'sex',
#     'age',
#     'max_heart_rate_achieved',
#     'exercise_induced_angina'
# ]
# 
# for col in columns_to_use:
# 
#     # THAL as string (NO mapping)
#     if col == "thal":
#         input_data[col] = st.selectbox(
#             "Thal",
#             ["normal", "reversible_defect", "fixed_defect"]
#         )
# 
#     # Only oldpeak as decimal
#     elif col == "oldpeak_eq_st_depression":
#         input_data[col] = st.number_input(
#             "Oldpeak (ST Depression)",
#             min_value=0.0,
#             max_value=100.0,
#             value=0.0,
#             step=0.1,
#             format="%.2f"
#         )
# 
# 
#     # All other columns as whole numbers
#     else:
#         input_data[col] = st.number_input(
#             col.replace("_", " ").title(),
#             min_value=0,
#             step=1,
#             format="%d"
#         )
# 
# # ==============================
# # Prediction Section
# # ==============================
# 
# if st.button("Predict"):
# 
#     # Convert dictionary to DataFrame
#     input_df = pd.DataFrame([input_data])
# 
#     # Make sure oldpeak is float
#     if "oldpeak" in input_df.columns:
#         input_df["oldpeak"] = input_df["oldpeak"].astype(float)
# 
#     # One-hot encode (for thal)
#     input_df = pd.get_dummies(input_df)
# 
#     # Match the training model columns exactly
#     input_df = input_df.reindex(columns=model_columns, fill_value=0)
# 
#     # Scale the input
#     input_scaled = scaler.transform(input_df)
# 
#     # Make prediction
#     prediction = model.predict(input_scaled)[0]
# 
#     # Show result
#     st.subheader("Prediction Result")
# 
#     if hasattr(model, "predict_proba"):
#         probability = model.predict_proba(input_scaled)[0][1]
#         st.write(f"Prediction Confidence: {round(probability * 100, 2)}%")
# 
#     if prediction == 1:
#         st.error("⚠ High Risk of Heart Disease Detected")
#     else:
#         st.success("✅ No Heart Disease Detected")

# for Colab Version only
!curl ipv4.icanhazip.com

import subprocess
subprocess.Popen(["streamlit", "run", "/content/streamlitapp.py", "--server.port", "8501", "--server.address", "0.0.0.0"])

!ngrok config add-authtoken "333qEsi4bxkebuFN1SWcsA8McYI_6pJKPmrzFqX5Yjr7NYtPi"

from pyngrok import ngrok
public_url = ngrok.connect(8501)
print("🌍 Public URL:", public_url)